"""auto-vote

Revision ID: 03c901835d1c
Revises: eab7c9a595bf
Create Date: 2022-07-11 15:20:47.824201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c901835d1c'
down_revision = 'eab7c9a595bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )
    # op.alter_column('posts', 'id',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=True,
    #                 autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('posts', 'id',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=False,
    #                 autoincrement=True)
    op.drop_table('votes')
    # ### end Alembic commands ###
